title: Hongli Ye
description: Mathematics student at SUSTech
theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax

header_pages:
  - index.md
  - _pages/about.md
  - _pages/blog.md
  - _pages/courses.md
  - _pages/seminars.md
